name: UE Automation Build
run-name: ${{ gitea.actor }} is building the project
on: [push]

jobs:
  build-linux-job:
    runs-on: ue-runner
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /media/blacksnow/devssd/code/UnrealEngine:/opt/UE
    
    steps:
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y git git-lfs wget apt-transport-https software-properties-common
          # 安装 .NET 6.0
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 6.0 --install-dir /usr/share/dotnet
          ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
          git lfs install

      - name: Manual Checkout Code
        # 使用环境变量直接拉取本地 Gitea 的代码，不走 GitHub
        run: |
          # 1. 清理目录

          git init
          TARGET_IP="172.18.0.2"
          git config --global http.sslVerify false
          # 彻底关闭压缩，因为是局域网，不需要 CPU 浪费时间去解压
          git config --global core.compression 0
          # 增加这一行，跳过 LFS 的预扫描（非常关键！）
          git config --global lfs.fetchexclude "*"

          echo "快速同步当前版本代码..."
          # 使用 --depth 1 且不带子模块，只取当前 commit 的快照
          git fetch --depth 1 "http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git" ${{ gitea.sha }}
          git checkout -f FETCH_HEAD

      - name: Check Files
        run: |
          echo "当前工作目录内容："
          ls -R | head -n 20
          find . -name "*.uproject"
          
      - name: Fix Engine Permissions
        run: |
          chmod +x /opt/UE/Engine/Build/BatchFiles/RunUAT.sh
          chmod +x /opt/UE/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool
          chmod -R +x /opt/UE/Engine/Binaries/Linux/

      - name: Compile and Build
        run: |
          ls -F ${{ github.workspace }}
          /opt/UE/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -project="${{ github.workspace }}/testLayr.uproject" \
          -targetplatform=Linux \
          -clientconfig=Development \
          -build -cook -stage -archive \
          -archivedirectory="${{ github.workspace }}/Saved/Builds" \
          -noP4 -utf8output -nocompileeditor