name: UE Automation Build
run-name: ${{ gitea.actor }} is building the project
on: [push]

jobs:
  build-linux-job:
    runs-on: ue-runner
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /media/blacksnow/devssd/code/UnrealEngine:/opt/UE
    
    steps:
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y git git-lfs wget apt-transport-https software-properties-common
          # 安装 .NET 6.0
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 6.0 --install-dir /usr/share/dotnet
          ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
          git lfs install

      - name: Manual Checkout Code
        # 使用环境变量直接拉取本地 Gitea 的代码，不走 GitHub
        run: |
          git init
          TARGET_IP="172.18.0.2"
          # 使用 Gitea 提供的 Token 构建带认证的 URL
          AUTH_URL="http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git"

          git config --global http.sslVerify false
          
          echo "1. 拉取基础代码..."
          git fetch --depth 1 "$AUTH_URL" ${{ gitea.sha }}
          git checkout -f FETCH_HEAD
          
          echo "2. 配置 LFS 认证环境..."
          git lfs install
          # 关键：直接将带认证的 URL 写入 lfs.url
          git config lfs.url "$AUTH_URL/info/lfs"
          # 增加这一行，强制 LFS 在当前上下文中使用该地址
          git config lfs.transfer.maxretries 10

          echo "3. 开始执行 LFS 资源下载 (显示详细进度)..."
          # 使用 -I 和 -X 参数之外的最稳妥写法
          git lfs pull origin

      - name: Check Files
        run: |
          echo "当前工作目录内容："
          ls -R | head -n 20
          find . -name "*.uproject"
          
      - name: Fix Engine Permissions
        run: |
          chmod +x /opt/UE/Engine/Build/BatchFiles/RunUAT.sh
          chmod +x /opt/UE/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool
          chmod -R +x /opt/UE/Engine/Binaries/Linux/

      - name: Compile and Build
        run: |
          # 1. 自动定位 .uproject 文件 (递归搜索)
          # find 会在当前目录下寻找任何以 .uproject 结尾的文件
          PROJECT_PATH=$(find ${{ github.workspace }} -name "*.uproject" -print -quit)
          
          echo "Checking directory structure:"
          ls -R ${{ github.workspace }} | head -n 20
          
          echo "---------------------------------------"
          if [ -z "$PROJECT_PATH" ]; then
            echo "❌ 错误：在仓库中没找到 .uproject 文件！请检查 Git 是否成功拉取了内容。"
            exit 1
          else
            echo "✅ 找到项目文件: $PROJECT_PATH"
          fi
          echo "---------------------------------------"

          # 2. 使用找到的变量执行编译
          /opt/UE/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -project="$PROJECT_PATH" \
          -targetplatform=Linux \
          -clientconfig=Development \
          -build -cook -stage -archive \
          -archivedirectory="${{ github.workspace }}/Saved/Builds" \
          -noP4 -utf8output -nocompileeditor