name: UE Automation Build
run-name: ${{ gitea.actor }} is building the project
on: [push]

jobs:
  build-linux-job:
    runs-on: ue-runner
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /media/blacksnow/devssd/code/UnrealEngine:/opt/UE
    
    steps:
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y git git-lfs wget apt-transport-https software-properties-common
          # 安装 .NET 6.0
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 6.0 --install-dir /usr/share/dotnet
          ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
          git lfs install

      - name: Manual Checkout Code
        # 使用环境变量直接拉取本地 Gitea 的代码，不走 GitHub
        run: |
          git init
          TARGET_IP="172.18.0.2"
          git config --global http.sslVerify false
          
          # 1. 先拉取基础代码结构
          git fetch --depth 1 "http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git" ${{ gitea.sha }}
          git checkout -f FETCH_HEAD
          
          # 2. 重新开启 LFS 并拉取（这是重点）
          git lfs install
          # 显式指定 LFS 地址，确保认证信息正确注入
          git config lfs.url "http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git/info/lfs"
          
          echo "开始拉取 LFS 资源，这可能需要较长时间..."
          # 限制并发为 4，既保证速度又防止死锁；增加 --progress 查看进度
          git config --global lfs.concurrenttransfers 4
          git lfs pull --progress

      - name: Check Files
        run: |
          echo "当前工作目录内容："
          ls -R | head -n 20
          find . -name "*.uproject"
          
      - name: Fix Engine Permissions
        run: |
          chmod +x /opt/UE/Engine/Build/BatchFiles/RunUAT.sh
          chmod +x /opt/UE/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool
          chmod -R +x /opt/UE/Engine/Binaries/Linux/

      - name: Compile and Build
        run: |
          # 1. 自动定位 .uproject 文件 (递归搜索)
          # find 会在当前目录下寻找任何以 .uproject 结尾的文件
          PROJECT_PATH=$(find ${{ github.workspace }} -name "*.uproject" -print -quit)
          
          echo "Checking directory structure:"
          ls -R ${{ github.workspace }} | head -n 20
          
          echo "---------------------------------------"
          if [ -z "$PROJECT_PATH" ]; then
            echo "❌ 错误：在仓库中没找到 .uproject 文件！请检查 Git 是否成功拉取了内容。"
            exit 1
          else
            echo "✅ 找到项目文件: $PROJECT_PATH"
          fi
          echo "---------------------------------------"

          # 2. 使用找到的变量执行编译
          /opt/UE/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -project="$PROJECT_PATH" \
          -targetplatform=Linux \
          -clientconfig=Development \
          -build -cook -stage -archive \
          -archivedirectory="${{ github.workspace }}/Saved/Builds" \
          -noP4 -utf8output -nocompileeditor