name: UE Automation Build
run-name: ${{ gitea.actor }} is building the project
on: [push]

jobs:
  build-linux-job:
    runs-on: ue-runner
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /media/blacksnow/devssd/code/UnrealEngine:/opt/UE
    
    steps:
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y git git-lfs wget apt-transport-https software-properties-common
          # 安装 .NET 6.0
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 6.0 --install-dir /usr/share/dotnet
          ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
          git lfs install

      - name: Manual Checkout Code
        # 使用环境变量直接拉取本地 Gitea 的代码，不走 GitHub
        run: |
          # 1. 清理目录

          git init
          TARGET_IP="172.18.0.2"
          
          # 1. 极致优化 Git 参数
          git config --global http.sslVerify false
          # 增大缓冲区到 500MB，防止大数据包导致中断
          git config --global http.postBuffer 524288000
          # 降低压缩率，减少 CPU 负担，加快局域网传输
          git config --global core.compression 0
          
          echo "开始拉取基础代码 (带详细进度)..."
          # 增加 --progress 强制显示进度，增加 --verbose 显示详细握手信息
          git fetch --progress --verbose --depth 1 "http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git" ${{ gitea.sha }}
          
          git checkout FETCH_HEAD
          
          # 先确认基础代码拉下来了，能看到 .uproject 为止
          ls -R
          
          echo "开始拉取 LFS 资源 (显示进度)..."
          git lfs install
          # 明确指定 LFS 远程地址，并增加进度条显示
          git config lfs.url "http://${{ gitea.actor }}:${{ secrets.GITHUB_TOKEN }}@${TARGET_IP}:3000/${{ gitea.repository }}.git/info/lfs"
          git lfs pull --progress

      - name: Fix Engine Permissions
        run: |
          chmod +x /opt/UE/Engine/Build/BatchFiles/RunUAT.sh
          chmod +x /opt/UE/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool
          chmod -R +x /opt/UE/Engine/Binaries/Linux/

      - name: Compile and Build
        run: |
          ls -F ${{ github.workspace }}
          /opt/UE/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -project="${{ github.workspace }}/testLayr.uproject" \
          -targetplatform=Linux \
          -clientconfig=Development \
          -build -cook -stage -archive \
          -archivedirectory="${{ github.workspace }}/Saved/Builds" \
          -noP4 -utf8output -nocompileeditor